"use client"

import { Bar, BarChart, CartesianGrid, XAxis, YAxis, Tooltip, Legend, ResponsiveContainer } from "recharts"
import { useMemo } from "react"

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import type { Sale, UserProfile } from "@/lib/data"


interface SalesBySalespersonChartProps {
  sales: Sale[];
  userProfiles: UserProfile[];
}

export function SalesBySalespersonChart({ sales, userProfiles }: SalesBySalespersonChartProps) {
  const chartData = useMemo(() => {
    const salesByPerson: Record<string, { name: string, sales: number }> = {};

    userProfiles.forEach(profile => {
      if (profile.role === 'Salesperson') {
        salesByPerson[profile.uid] = { name: profile.name.split(' ')[0], sales: 0 };
      }
    });

    sales.forEach(sale => {
      if (salesByPerson[sale.salespersonId]) {
        salesByPerson[sale.salespersonId].sales += sale.amount;
      }
    });

    return Object.values(salesByPerson);
  }, [sales, userProfiles]);
  
  return (
    <Card className="col-span-1 lg:col-span-3 print:border-0 print:shadow-none">
      <CardHeader>
        <CardTitle className="font-headline">Sales by Salesperson</CardTitle>
        <CardDescription>Total sales revenue generated by each salesperson.</CardDescription>
      </CardHeader>
      <CardContent className="pl-2">
        <ResponsiveContainer width="100%" height={350}>
          <BarChart data={chartData}>
            <CartesianGrid strokeDasharray="3 3" vertical={false} />
            <XAxis dataKey="name" stroke="#888888" fontSize={12} tickLine={false} axisLine={false} />
            <YAxis stroke="#888888" fontSize={12} tickLine={false} axisLine={false} tickFormatter={(value) => `$${value/1000}k`} />
            <Tooltip
              contentStyle={{
                backgroundColor: 'hsl(var(--background))',
                borderColor: 'hsl(var(--border))',
                borderRadius: 'var(--radius)',
              }}
              labelStyle={{
                color: 'hsl(var(--foreground))'
              }}
            />
            <Legend iconSize={10} />
            <Bar dataKey="sales" name="Total Sales" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} />
          </BarChart>
        </ResponsiveContainer>
      </CardContent>
    </Card>
  )
}
